### ISSUE TITLE
how many epochs did you train? 

### ISSUE THREAD

**Issue by Moran232** [d-li14/mobilenetv2.pytorch#7]
Hi, thanks for your nice work.
I am wandering how many epochs you trained?   the default epochs=90 in your code and it may take around 60hrs.  while the lr policy you set is more than 90 epochs .

**Comment by nzmora** [comment]
Hi,

I am also interested in understanding how you created the pre-trained models.  I'm the author of [NN Distiller](https://github.com/NervanaSystems/distiller), and I'd like to point our users to the pretrained mobilenet_v2 in your repository, but it is much better if we know the training hyper-parameters (this is because we need to use them, after pruning/compression for the fine-tuning phase).

If you can provide the full command-line, that would be best.  If this is not possible, please provide the initial LR, LR decay policy, the number of epochs trained, the batch size, WD.

Thank you!
Neta

**Comment by d-li14** [comment]
Hi Neta,

This repo is actually also associated with some works during my internship at Intel Labs China. Please check your Intel e-mail for more information. If you have further questions, feel free to contact me anytime. @nzmora

Regards,
Duo

**Comment by d-li14** [comment]
@nzmora Please refer to https://github.com/d-li14/mobilenetv2.pytorch/blob/master/README.md#training for the full command line to reproduce.
